#pragma config(Motor,  port6,           LF,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           LB,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           RF,            tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           RB,            tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard

task main()
{
	//wheel
			motor[LF] = vexRT[Ch4] + vexRT[Ch3] + vexRT[Ch1];
			motor[LB] = (-vexRT[Ch4]) + vexRT[Ch3] + vexRT[Ch1];
			motor[RF] = vexRT[Ch4] - vexRT[Ch3] + vexRT[Ch1];
			motor[RB] = (-vexRT[Ch4]) -vexRT[Ch3] + vexRT[Ch1];
}
